name: Build
#on: [push, pull_request]
on: [workflow_dispatch] # manual tigger

jobs:
  build_wheels:
    name: Make ${{ matrix.os }} ${{ matrix.cibw_arch }} wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        pybuild: ["cp37-*", "cp38-*" ,"cp39-*"]
        exclude:
          - os: ubuntu-latest
            cibw_arch: aarch64            
            cibw_build: "cp37-*"        

    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
             python-version: '3.7'
             
      - if: startsWith(runner.os, 'Windows') && ( matrix.pybuild =="cp37-*" ||matrix.pybuild =="cp38-*")
        shell: cmd
        run:  copy  pyproject_np1.17.3_miw3738.toml  pyproject.toml       
      - if: startsWith(runner.os, 'Windows') &&  matrix.pybuild =="cp39-*" 
        shell: cmd
        run:  copy  pyproject_np1.19.3_miw39.toml  pyproject.toml 
      - if: startsWith(runner.os, 'Windows') &&  matrix.pybuild =="cp310-*" 
        shell: cmd
        run:  copy pyproject_np1.21.3_miwma310.toml  pyproject.toml         
      - if: startsWith(runner.os, 'Windows') &&  matrix.pybuild =="cp311-*" 
        shell: cmd
        run:  copy pyproject_np1.23.2_miwma311.toml  pyproject.toml  

      - if: startsWith(runner.os, 'Windows')
        run:  type  pyproject.toml 
      
      - name: Build wheels ....
        uses: pypa/cibuildwheel@v2.16.1
        env:
          #CIBW_ARCHS_MACOS:        x86_64 arm64
          CIBW_BUILD:   ${{ matrix.pybuild }}            #cp38-*  cp39-*
          
 
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
