name: Build
#on: [push, pull_request]
on: [workflow_dispatch] # manual tigger

jobs:
  build_wheels_macos:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-11]
        cibw_build: ["cp37-* cp38-* "]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        name: Install Python
        with:
             python-version: '3.7'
             
      - name: Copy Project.toml 38 39
        run: |            
             cp  pyproject_np1.21.0_ma3839.toml  pyproject.toml       
      - name: Build wheels3839
        uses: pypa/cibuildwheel@v2.16.1
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_BUILD: cp38-*  cp39-*
          
      - name: Copy Project.toml 310
        run: |            
             cp  pyproject_np1.21.3_miwma310.toml  pyproject.toml       
      - name: Build wheels310
        uses: pypa/cibuildwheel@v2.16.1
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_BUILD: cp310-* 
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
