name: Build
on: [push, pull_request]
#on: [workflow_dispatch] # manual tigger
#env:
   #PYVERSION: "cp37-*"

jobs:
  build_wheels:
    name: Make ${{ matrix.os }} wheels for  ${{ matrix.pybuild }}
    runs-on: ${{ matrix.os }}
    env:
      PYVERSION: "cp37-*"
    strategy:
      fail-fast: true
      matrix:
        os:      [windows-latest]
        #pybuild: ["cp37-*", "cp38-*" ,"cp39-*"]
        exclude:
          - os: ubuntu-latest
            #cibw_arch: aarch64            
            #pybuild: "cp37-*"        

    steps:
      #echo "::set-env name=PYVERSION::cp3dd-*"             
      #if: startsWith(runner.os, 'Windows') && ( matrix.pybuild=='cp37-*' ||matrix.pybuild =='cp38-' )
      
      - if: startsWith(runner.os, 'Windows')
        shell:  pwsh #cmd
        run: |
             echo "PYVERSION=cp3dd-xyyy" >>  $env:GITHUB_ENV
 
        
      - run:  echo $env:PYVERSION
        shell: pwsh 
 
        