name: Build

on: [push, pull_request]


jobs:
  build_wheels_macos:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
        cibw_build: ["cp37-* cp38-* "]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.1
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
