name: Build
on: [push, pull_request]
#on: [workflow_dispatch] # manual tigger

jobs:
  build_wheels:
    name: Make ${{ matrix.os }} wheels for  ${{ matrix.pybuild }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:      [windows-latest]
        #pybuild: ["cp37-*", "cp38-*" ,"cp39-*"]
        exclude:
          - os: ubuntu-latest
            #cibw_arch: aarch64            
            #pybuild: "cp37-*"        

    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
             python-version: '3.7'
             
      #if: startsWith(runner.os, 'Windows') && ( matrix.pybuild=='cp37-*' ||matrix.pybuild =='cp38-' )
     -  if: startsWith(runner.os, 'Windows')
        shell: cmd
        run:  copy  pyproject_np1.17.3_miw3738.toml  pyproject.toml 
        uses: pypa/cibuildwheel@v2.16.1
        env:
             #CIBW_ARCHS_MACOS:        x86_64 arm64
             CIBW_ARCHS:   AMD64 #all, native AMD64 x86 ARM64
             CIBW_BUILD:   cp37-*  cp38-*        
   
     -  if: startsWith(runner.os, 'Windows')     
        run:  copy  pyproject_np1.19.3_miw39.toml  pyproject.toml 
        uses: pypa/cibuildwheel@v2.16.1
        env:
             #CIBW_ARCHS_MACOS:        x86_64 arm64  AMD64 x86 ARM64
             CIBW_ARCHS:   AMD64 #all, native AMD64 x86 ARM64             
             CIBW_BUILD:   cp39-* 

     -  if: startsWith(runner.os, 'Windows')     
        run:  copy pyproject_np1.21.3_miwma310.toml  pyproject.toml 
        uses: pypa/cibuildwheel@v2.16.1
        env:
             #CIBW_ARCHS_MACOS:        x86_64 arm64
             CIBW_ARCHS:   AMD64 #all, native AMD64 x86 ARM64             
             CIBW_BUILD:   cp310-*    

     -  if: startsWith(runner.os, 'Windows')     
        run:  copy pyproject_np1.23.2_miwma311.toml pyproject.toml 
        uses: pypa/cibuildwheel@v2.16.1
        env:
             #CIBW_ARCHS_MACOS:        x86_64 arm64
             CIBW_ARCHS:   AMD64 #all, native AMD64 x86 ARM64             
             CIBW_BUILD:   cp311-*              
             
       - if: startsWith(runner.os, 'Windows')
        run: |
             type  pyproject.toml 
             echo ${{ matrix.pybuild }}
      
 
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
