name: Build
on: [push, pull_request]
#on: [workflow_dispatch] # manual tigger
env:
   PYVERSION: "cp37-*"

jobs:
  build_wheels:
    name: Make ${{ matrix.os }} wheels for  ${{ matrix.pybuild }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:      [windows-latest]
        #pybuild: ["cp37-*", "cp38-*" ,"cp39-*"]
        exclude:
          - os: ubuntu-latest
            #cibw_arch: aarch64            
            #pybuild: "cp37-*"        

    steps:
      #echo "::set-env name=PYVERSION::cp3dd-*"             
      #if: startsWith(runner.os, 'Windows') && ( matrix.pybuild=='cp37-*' ||matrix.pybuild =='cp38-' )
      
      - if: startsWith(runner.os, 'Windows')
        shell: cmd
        run: |
             echo "PYVERSION=cp3dd-*" >> $GITHUB_ENV 
        
      - run: echo $PYVERSION && echo "PYVERSION=cp3dd333-*" >> $GITHUB_ENV 
      - run: echo $PYVERSION && echo "PYVERSION=cp3dd33xx3-*" >> $GITHUB_ENV 
        