name: Build
on: [push, pull_request]
#on: [workflow_dispatch] # manual tigger


jobs:
  build_wheels_musl_linux:
    name: Make ${{ matrix.os }} wheels  
    runs-on: ${{ matrix.os }}
    env:
      arch:   x86_64  #  aarch64 x86_64
      CIBW_SKIP:   '*-musllinux_aarch64' 
    strategy:
      fail-fast: true
      matrix:
        os:      [ubuntu-latest]    

    steps:  
  
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
             python-version: '3.9'
                  
      - run: cp pyproject_np1.25.0_musl_39310311.toml pyproject.toml 
      - uses: pypa/cibuildwheel@v2.16.1
        env:             
             CIBW_ARCHS:   ${{env.arch}}   #all, native AMD64 x86 ARM64
             CIBW_BUILD:  cp39-*musllinux*  cp310-*musllinux*  cp311-*musllinux*     
              
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          
             
 