name: NewBuildAlL
#on: [push, pull_request]
#on: [workflow_dispatch]  # manual tigger
on:
  workflow_dispatch:
    inputs:
      should_upload:
        description: 'Upload to PyPI'
        required: true
        default: "NO"
        type: choice
        options:
          - 'NO'
          - 'YES'

jobs:

############################################################################
#    Build Sdist
############################################################################
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6      # downloads the code from the GitHub repository onto the runner      
      - uses: actions/setup-python@v6
 
      - name: Check metadata
        run: "python setup.py check"
      - name: Build sdist
        #run: "python setup.py sdist && ls -l dist"  # Generate uppercase filename not accepted by PyPI
        run "pip install build && python -m build --sdist" 

      - uses: actions/upload-artifact@v4
        with:
          name: sdist_artifact       # if missing, the default name is artifact
          path: ./dist/*.tar.gz
          
############################################################################
#    Build Wheels for windows
############################################################################          
  build_wheels_win:
    name: Make ${{ matrix.os }} wheels  
    runs-on: ${{ matrix.os }}
    env:
      arch: AMD64 
    strategy:
      fail-fast: true
      matrix:
        os:   [windows-latest]    

    steps:       
      # downloads your code from your GitHub repository onto the runner
      - uses: actions/checkout@v6   
      
      # 1. First Build Pass: Legacy Versions (cp37-cp38)
      - name: Install Python (Legacy)
        uses: actions/setup-python@v6
        with:
             python-version: '3.10'
 
      - run:  copy  pyproject_np1.17.3_miw3738.toml  pyproject_NotUsed.toml
      - uses: pypa/cibuildwheel@v2.16.5
        env:             
             CIBW_ARCHS:   ${{env.arch}}   #all, native AMD64 x86 ARM64
             CIBW_BUILD:   cp37-*  cp38-*  cp39-* cp310-*       
   

      # 2. Second Build Pass: Modern Versions (cp39-cp314)
      - name: Install Python (Legacy)
        uses: actions/setup-python@v6
        with:
             python-version: '3.14'
             
      - run:  copy  pyproject_np1.19.3_miw39.toml  pyproject_NotUsed.toml 
      - uses: pypa/cibuildwheel@v3.4.1
        env:             
             CIBW_ARCHS:   ${{env.arch}}   #all, native AMD64 x86 ARM64
             CIBW_BUILD:   cp311-*  cp312-*  cp313-*  cp314-*
             #CIBW_ARCHS_MACOS:    x86_64 arm64   
             #CIBW_BEFORE_BUILD: cp pyproject_np1.17.3_miw3738.toml pyproject.toml             
            
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-windows       # Add this        
          path: ./wheelhouse/*.whl

############################################################################
#    Build Wheels for Linux (manyliux)
############################################################################  
        
  build_wheels_linux:
    name: Make ${{ matrix.os }} wheels  - x86_64 
    runs-on: ${{ matrix.os }}
    env:
      arch: x86_64 #  aarch64
      CIBW_SKIP:   '*-musllinux_*' 
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
    strategy:
      fail-fast: true
      matrix:
        os:      [ubuntu-latest]    

    steps:       
      - uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with:
             python-version: '3.14'
 
      - run:  cp  pyproject_np1.17.3_miw3738.toml  pyproject_NotUsed.toml # pyproject.toml
      - uses: pypa/cibuildwheel@v3.4.1
        env:             
             CIBW_ARCHS:   ${{env.arch}}   #all, native AMD64 x86 ARM64
             CIBW_BUILD:   cp38-*   cp39-*  cp310-* cp311-*  cp312-*   cp313-*   cp314-*      # cp37-*  (not supported by v3 and only by v2)
              
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-x86_64  # Add this        
          path: ./wheelhouse/*.whl
          
############################################################################
#    Build Wheels for Linux (manyliux-aarch64) 
############################################################################             
  build_wheels_linux_aarch64:
    name: Make ${{ matrix.os }} wheels  - aarch64
    runs-on: ${{ matrix.os }}
    env:
      arch:   aarch64  #  aarch64 x86_64
      CIBW_SKIP:   '*-musllinux_*' 
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
    strategy:
      fail-fast: true
      matrix:
        os:      [ubuntu-latest]    

    steps:  
  
      - uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with:
             python-version: '3.14'
 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64    #all
   
      - run: cp  pyproject_np1.19.3_miw39.toml  pyproject_NotUed.toml 
      - uses: pypa/cibuildwheel@v3.4.1
        env:             
             CIBW_ARCHS:   ${{env.arch}}   #all, native AMD64 x86 ARM64
             CIBW_BUILD:  cp38-*   cp39-*  cp310-* cp311-*  cp312-*   cp313-*   cp314-*     #  cp37-*   
       
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-aarch64  # Add this        
          path: ./wheelhouse/*.whl

############################################################################
#    Build Wheels for Linux (musl-linux-x86) 
############################################################################            

  build_wheels_musl_linux:
    name: Make ${{ matrix.os }} wheels  -musllinux(x86_64 )
    runs-on: ${{ matrix.os }}
    env:
      arch:   x86_64  #  aarch64 x86_64
      CIBW_SKIP:   '*-musllinux_aarch64' 
    strategy:
      fail-fast: true
      matrix:
        os:      [ubuntu-latest]    

    steps:  
  
      - uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with:
             python-version: '3.14'
                  
      - run: cp pyproject_np1.25.0_musl_39310311.toml pyproject_NotUed.toml 
      - uses: pypa/cibuildwheel@v3.4.1
        env:             
             CIBW_ARCHS:   ${{env.arch}}   #all, native AMD64 x86 ARM64
             CIBW_BUILD:  cp39-*musllinux*  cp310-*musllinux*  cp311-*musllinux*   cp312-*musllinux*   cp313-*musllinux*  cp314-*musllinux*  
              
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-musl-linux  # Add this
          path: ./wheelhouse/*.whl

############################################################################
#    Build Wheels for MacOS
############################################################################   
  build_wheels_mac:
    name: Make ${{ matrix.os }} wheels  
    runs-on: ${{ matrix.os }}
    env:
      arch:   x86_64  #  aarch64 x86_64
      CIBW_SKIP:   '*-musllinux_aarch64' 
    strategy:
      fail-fast: true
      max-parallel: 5
      matrix:
        os:      [macos-latest]    #[macos-12]    

    steps:  
  
      - uses: actions/checkout@v6
      
      - name: Install Python
        uses: actions/setup-python@v6
        with:
             python-version: '3.14'
                  
      - run: cp pyproject_np1.17.3_miw3738.toml pyprojectNotUSED.toml 
      - uses: pypa/cibuildwheel@v3.4.1
        env:             
             CIBW_ARCHS:  x86_64  arm64  #all, native AMD64 x86 ARM64
             CIBW_BUILD:   cp38-*  cp39-*   cp310-*  cp311-*    cp312-*   cp313-*   cp314-*  # cp37-*  
          
             
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-macos  # Add this    
          path: ./wheelhouse/*.whl		            

############################################################################
#   Merge all artificats into one file
############################################################################             
  merge_artifacts:
    name: Merge All Artifacts
    runs-on: ubuntu-latest
    needs: [build_sdist, build_wheels_win, build_wheels_linux, build_wheels_linux_aarch64, build_wheels_musl_linux, build_wheels_mac]

    # This line triggers the manual "Approve" button in GitHub
    environment: production 

    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: all-build-artifacts  # The final name for your single zip file
          pattern: '*'               # Merges all artifacts found in this workflow run
          delete-merged: true        # Optional: Deletes the individual small artifacts after merging

          
############################################################################
#   Upload the wheels into PyPI
############################################################################          
  upload_pypi:
    name:   Upload to PyPI (prod)
    needs: [ merge_artifacts ]
    runs-on: ubuntu-22.04
    #if: github.repository == 'tornadoweb/tornado' && github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    if: ${{ github.event.inputs.should_upload == 'YES' }} 
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: all-build-artifacts 
          path: dist          
          #pattern: '*'         # Grabs all unique artifacts (wheels + sdist)
          #merge-multiple: true # Flattens them all into the 'dist' folder          

      # --- Make sure all files name are in lowercase because PyPI's normalization rules--
      # Use tr (translate) command to convert all uppercase letters to lowercase
      - name: Rename artifacts to lowercase
        run: |
          cd dist
          for f in *; do
            lowercased=$(echo "$f" | tr '[:upper:]' '[:lower:]')
            if [ "$f" != "$lowercased" ]; then
              mv "$f" "$lowercased"
              echo "Renamed: $f -> $lowercased"
            fi
          done
          
      #- uses: pypa/gh-action-pypi-publish@v1.5.0
      - uses: pypa/gh-action-pypi-publish@release/v1    
        with:
          user:     __token__  # zhaokg
          password: ${{secrets.PYPI_PASSWORD}} 
          # The next two lines are for uploading to test.pypi
          #password: ${{ secrets.TEST_PYPI_ORG_PASSWORD }} 
          #repository_url: https://test.pypi.org/legacy/
          