name: NewBuildAll_NoUpload
#on: [push, pull_request]
#on: [workflow_dispatch]  # manual tigger
on:
  workflow_dispatch:
    inputs:
      upload_flag:
        description: 'Upload to PyPI'
        required: true
        default: 'NO'
        type: choice
        options:
          - NO
          - YES


jobs:

############################################################################
#    Build Sdist
############################################################################
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6      # downloads your code from your GitHub repository onto the runner      
      - uses: actions/setup-python@v6
 
      - name: Check metadata
        run: "python setup.py check"
      - name: Build sdist
        run: "python setup.py sdist && ls -l dist"

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.tar.gz
          
############################################################################
#    Build Wheels for windows
############################################################################          
  build_wheels_win:
    name: Make ${{ matrix.os }} wheels  
    runs-on: ${{ matrix.os }}
    env:
      arch: AMD64 
    strategy:
      fail-fast: true
      matrix:
        os:   [windows-latest]    

    steps:       
      # downloads your code from your GitHub repository onto the runner
      - uses: actions/checkout@v6   
      
      # 1. First Build Pass: Legacy Versions (cp37-cp38)
      - name: Install Python (Legacy)
        uses: actions/setup-python@v6
        with:
             python-version: '3.10'
 
      - run:  copy  pyproject_np1.17.3_miw3738.toml  pyproject_NotUsed.toml
      - uses: pypa/cibuildwheel@v2.16.5
        env:             
             CIBW_ARCHS:   ${{env.arch}}   #all, native AMD64 x86 ARM64
             CIBW_BUILD:   cp310-* cp311-*         
            
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-windows       # Add this        
          path: ./wheelhouse/*.whl

    
          
  upload_pypi:
    name: Upload to PyPI (prod)
    needs: [ build_wheels_win]
    runs-on: ubuntu-22.04
    #if: github.repository == 'tornadoweb/tornado' && github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    if: ${{ github.event.inputs.upload_flag }}  == 'YES'    
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels-windows
          path: dist          
          #pattern: '*'       # Grabs all unique artifacts (wheels + sdist)
          #merge-multiple: true # Flattens them all into the 'dist' folder          

      #- uses: pypa/gh-action-pypi-publish@v1.5.0
      - uses: pypa/gh-action-pypi-publish@release/v1    
        with:
          user: __token__  # zhaokg
          #password: ${{ secrets.PYPI_PASSWORD }}            # The official PyPI site
          password: ${{ secrets.TEST_PYPI_ORG_PASSWORD }} 
          repository_url: https://test.pypi.org/legacy/
          