name: test
#on: [push, pull_request]
on: [workflow_dispatch] # manual tigger
env:
  WORKFLOW_VAR: workflow_variable 

jobs:
  build_wheels:
    name: Make ${{ matrix.os }} wheels for  ${{ matrix.pybuild }}
    runs-on: ${{ matrix.os }}
    env:
      JOB_VAR: "I am a job variable..."
    strategy:
      fail-fast: true
      matrix:
        os:      [ubuntu-latest, windows-latest]
        pybuild: [ "cp37-*", "cp38-*" ]
        exclude:
          - os: ubuntu-latest            
          - os: windows-latest
            pybuild: "cp38-*"            
        #include:
        #  - os:  macos_latest
 
    steps:    
      #https://stackoverflow.com/questions/66733076/github-actions-set-environment-variable-for-windows-build-with-powershell     
      - if: startsWith(runner.os, 'Windows') && ${{ matrix.pybuild }} == 'cp37-*'
        run:    echo "MY_ENV_VAR=a quick test" >>  $env:GITHUB_ENV        
        shell:  pwsh                               # cmd
      - if: startsWith(runner.os, 'Windows')
        run:  echo $env:MY_ENV_VAR
        shell: pwsh 
        env:
           MY_ENV_NEW_VAR: ${{ env.MY_ENV_VAR }}
           
      - if: startsWith(runner.os, 'Windows') && ${{ matrix.pybuild }} == 'cp37-*'
        run:    echo "MY_ENV_VAR=a quick test" >>  $env:GITHUB_ENV        
        shell:  pwsh                               # cmd
        
      - if: startsWith(runner.os, 'Linux')
        run:    echo "MY_ENV_VAR=a quick test" >>  $GITHUB_ENV  
      - run:  echo $MY_ENV_VAR 
        if: startsWith(runner.os, 'Linux')      
 
 
    